//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCita { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idClinica { get; set; }
        public Nullable<int> idDueno { get; set; }
        public Nullable<int> idTipo { get; set; }
        public Nullable<int> idVeterinario { get; set; }
    
        public virtual Clinicas Clinicas { get; set; }
        public virtual Duenos Duenos { get; set; }
        public virtual TipoCitas TipoCitas { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
    }
}
