//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clinicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinicas()
        {
            this.Citas = new HashSet<Citas>();
        }

        [Required(ErrorMessage = "Digite un id")]
        public int idClinica { get; set; }

        [Required(ErrorMessage = "Digite un numero de telefono")]
        [Display(Name = "Teléfono")]
        public Nullable<int> telefono { get; set; }

        [Required(ErrorMessage = "Digite una dirección")]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }

        [Required(ErrorMessage = "Seleccione la provincia")]
        public Nullable<int> idProvincia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Citas> Citas { get; set; }

        public virtual Provincias Provincias { get; set; }
    }
}
