//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enfermedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enfermedades()
        {
            this.Historiales = new HashSet<Historiales>();
        }

        [Required(ErrorMessage = "Digite el id")]
        public int idEnfermedad { get; set; }

        [Required(ErrorMessage = "Digite nombre de la enfermedad")]
        [StringLength(16, ErrorMessage = "Nombre muy largo")]
        public string nombreEnfermedad { get; set; }

        [Required(ErrorMessage = "Digite la descripción de la enfermedad")]
        [StringLength(16, ErrorMessage = "Descripción muy larga")]
        public string descEnfermedad { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historiales> Historiales { get; set; }
    }
}
