//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Historiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historiales()
        {
            this.Mascotas = new HashSet<Mascotas>();
        }

        [Required(ErrorMessage = "Digite el id")]
        public int idHistorial { get; set; }

        [Required(ErrorMessage = "Seleccione la fecha")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> fecha { get; set; }

        [Required(ErrorMessage = "Digite el motivo de la consulta")]
        [Display(Name = "Motivo de la Consulta")]
        public string motivoConsulta { get; set; }

        [Required(ErrorMessage = "Digite el diagnostico")]
        [Display(Name = "Diagnóstico")]
        public string dignostico { get; set; }

        [Required(ErrorMessage = "Seleccione la enfermedad")]
        public Nullable<int> idEnfermedad { get; set; }

        [Required(ErrorMessage = "Seleccione el veterinario")]
        public Nullable<int> idVeterinario { get; set; }


        public virtual Enfermedades Enfermedades { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mascotas> Mascotas { get; set; }
    }
}
