//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mascotas
    {

        [Required(ErrorMessage = "Digite el id")]
        public int idMascotas { get; set; }

        [Required(ErrorMessage = "Digite el nombre")]
        [StringLength(16, ErrorMessage = "Nombre muy largo")]
        [Display(Name = "Nombre de la mascota")]
        public string nombreMascota { get; set; }

        [Required(ErrorMessage = "Seleccione la raza")]
        public Nullable<int> idRaza { get; set; }

        [Required(ErrorMessage = "Digite la edad")]
        [Display(Name = "Edad")]
        public Nullable<int> edad { get; set; }

        [Required(ErrorMessage = "Digite el id del historial")]
        public Nullable<int> idHistorial { get; set; }

        [Required(ErrorMessage = "Seleccione el dueño")]
        public Nullable<int> idDueno { get; set; }


        public virtual Duenos Duenos { get; set; }
        public virtual Historiales Historiales { get; set; }
        public virtual Razas Razas { get; set; }
    }
}
